name: Call Build

on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: UTC

jobs:
  openwrt:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        id: openwrt
        working-directory: /
        env:
          workflow: "build-openwrt"
        run: |
          data='
          {
            "ref": "main",
            "inputs": {
              "openwrt_branch": "openwrt;main",
              "device_branch": "mt7981"
            }
          }'
          curl -XPOST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.workflow }}.yml/dispatches \
          --data "$data"

  immortalwrt:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        id: immortalwrt
        working-directory: /
        env:
          workflow: "build-openwrt"
        run: |
          data='
          {
            "ref": "main",
            "inputs": {
              "openwrt_branch": "immortalwrt;master",
              "device_branch": "mt7981"
            }
          }'
          curl -XPOST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.workflow }}.yml/dispatches \
          --data "$data"

  immortalwrt-mt798x:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        id: immortalwrt-mt798x
        working-directory: /
        env:
          workflow: "build-openwrt"
        run: |
          data='
          {
            "ref": "main",
            "inputs": {
              "openwrt_branch": "immortalwrt-mt798x;openwrt-21.02",
              "device_branch": "mt7981"
            }
          }'
          curl -XPOST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.workflow }}.yml/dispatches \
          --data "$data"

  u-boot:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        id: u-boot
        working-directory: /
        env:
          workflow: "build-u-boot"
        run: |
          data='
          {
            "ref": "main",
            "inputs": {
              "openwrt_branch": "u-boot",
              "device_branch": "all"
            }
          }'
          curl -XPOST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.workflow }}.yml/dispatches \
          --data "$data"
